
package Mainsito;

import Clases.AdministrarClientes;
import Clases.AdministrarProveedores;
import Clases.*;
import Compras.NuevaCompra;
import Ventas.*;
import Formularios.*;
import Proveedores.*;
import Productos.*;
import Compras.*;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Menu extends javax.swing.JFrame {

    public static Conexion con;
    private static AdministrarClientes adminC;
    private static AdministrarProveedores adminPro;
    private static AdministrarProductos adminP;
    private static  AdminVentasCompras adminCV;
    private String contra = "12345";

    public Menu() {
        boolean ban = true;
        Connection cn;
        String contra2;
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            con = new Conexion();
        } catch (Exception e) {
            ingresarServeryPuerto();
        }

        setIconImage(new ImageIcon(getClass().getResource("/imagenes/manzanita.png")).getImage());
        cn = null;
        int reply;
        do {
            reply = JOptionPane.NO_OPTION;
            try {
                con.conectar();
                cn = con.getConnection();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex,
                         "Error inesperado", JOptionPane.ERROR_MESSAGE);
                reply = JOptionPane.showConfirmDialog(null,
                         "No funciono,¿ desea intentarlo de nuevo?\n",
                         "Conexion imposible de realizar",
                         JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    ingresarServeryPuerto();
                } else {
                    System.exit(0);
                }
            }
        } while (reply == JOptionPane.YES_OPTION);

        do {
            ban = true;
            contra2 = javax.swing.JOptionPane.showInputDialog(null, "Contraseña:",
                     "Ingresar contraseña", javax.swing.JOptionPane.PLAIN_MESSAGE);
            if (contra.equals(contra2)) {
                adminP = new AdministrarProductos(cn);
                adminCV = new AdminVentasCompras(cn);
                adminPro = new AdministrarProveedores(cn);
                adminC = new AdministrarClientes(cn);
            } else if (contra2 == null) {
                System.exit(0);
            } else {
                ban = false;
                JOptionPane.showMessageDialog(this, "La contraseña introducida no coincide",
                         "Contraseña incorrecta", JOptionPane.ERROR_MESSAGE);
            }
        } while (!ban);
    }

    private void ingresarServeryPuerto() {
        String servidor, puerto;
        servidor = javax.swing.JOptionPane.showInputDialog(null, "Servidor:",
                 "Ingresar el nombre del servidor", javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (servidor == null) {
            System.exit(0);
        }
        puerto = javax.swing.JOptionPane.showInputDialog(null, "Puerto:",
                 "Ingresar el puerto", javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (puerto == null) {
            System.exit(0);
        }
        con = new Conexion(servidor, puerto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MeClientes = new javax.swing.JMenu();
        agregarCliente = new javax.swing.JMenuItem();
        ConsultGeneralClientes = new javax.swing.JMenuItem();
        ModificarCliente = new javax.swing.JMenuItem();
        EliminarCliente = new javax.swing.JMenuItem();
        ConsultaIndCliente = new javax.swing.JMenuItem();
        MeProv = new javax.swing.JMenu();
        agregarProveedor = new javax.swing.JMenuItem();
        consultaProveedor = new javax.swing.JMenuItem();
        modificarProveedor = new javax.swing.JMenuItem();
        EliminarProveedor = new javax.swing.JMenuItem();
        ConsuIndProv = new javax.swing.JMenuItem();
        MeProd = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        MeVentas = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        MeCompras = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fruteria Lugo");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FrutasG.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 690));

        MeClientes.setText("Clientes");
        MeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeClientesActionPerformed(evt);
            }
        });

        agregarCliente.setText("Agregar");
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        MeClientes.add(agregarCliente);

        ConsultGeneralClientes.setText("Consultar");
        ConsultGeneralClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultGeneralClientesActionPerformed(evt);
            }
        });
        MeClientes.add(ConsultGeneralClientes);

        ModificarCliente.setText("Modificar");
        ModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarClienteActionPerformed(evt);
            }
        });
        MeClientes.add(ModificarCliente);

        EliminarCliente.setText("Eliminar");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });
        MeClientes.add(EliminarCliente);

        ConsultaIndCliente.setText("Consulta Individual");
        ConsultaIndCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaIndClienteActionPerformed(evt);
            }
        });
        MeClientes.add(ConsultaIndCliente);

        jMenuBar1.add(MeClientes);

        MeProv.setText("Proveedores");

        agregarProveedor.setText("Agregar");
        agregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProveedorActionPerformed(evt);
            }
        });
        MeProv.add(agregarProveedor);

        consultaProveedor.setText("Consultar");
        consultaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaProveedorActionPerformed(evt);
            }
        });
        MeProv.add(consultaProveedor);

        modificarProveedor.setText("Modificar");
        modificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProveedorActionPerformed(evt);
            }
        });
        MeProv.add(modificarProveedor);

        EliminarProveedor.setText("Eliminar");
        EliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProveedorActionPerformed(evt);
            }
        });
        MeProv.add(EliminarProveedor);

        ConsuIndProv.setText("Consulta Individual");
        ConsuIndProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsuIndProvActionPerformed(evt);
            }
        });
        MeProv.add(ConsuIndProv);

        jMenuBar1.add(MeProv);

        MeProd.setText("Productos");

        jMenuItem11.setText("Nuevo");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        MeProd.add(jMenuItem11);

        jMenuItem12.setText("Consultar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        MeProd.add(jMenuItem12);

        jMenuItem13.setText("Modificar");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        MeProd.add(jMenuItem13);

        jMenuItem14.setText("Eliminar");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        MeProd.add(jMenuItem14);

        jMenuItem15.setText("Consulta Individual");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        MeProd.add(jMenuItem15);

        jMenuBar1.add(MeProd);

        MeVentas.setText("Ventas");

        jMenuItem16.setText("Realizar Venta");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        MeVentas.add(jMenuItem16);

        jMenuItem17.setText("Consultar");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        MeVentas.add(jMenuItem17);

        jMenuItem18.setText("Eliminar");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        MeVentas.add(jMenuItem18);

        jMenuItem19.setText("Consulta Individual");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        MeVentas.add(jMenuItem19);

        jMenuBar1.add(MeVentas);

        MeCompras.setText("Compras");

        jMenuItem20.setText("Realizar Compra");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        MeCompras.add(jMenuItem20);

        jMenuItem21.setText("Consultar");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        MeCompras.add(jMenuItem21);

        jMenuItem22.setText("Eliminar");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        MeCompras.add(jMenuItem22);

        jMenuItem23.setText("Consulta Inidividual");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        MeCompras.add(jMenuItem23);

        jMenuBar1.add(MeCompras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
        FClientes cl = new FClientes(adminC);

    }//GEN-LAST:event_agregarClienteActionPerformed

    private void agregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProveedorActionPerformed
        FProveedores fp = new FProveedores(adminPro);
        fp.setVisible(true);
    }//GEN-LAST:event_agregarProveedorActionPerformed

    private void modificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProveedorActionPerformed
        FModificarPro mp = new FModificarPro(adminPro);
        mp.setVisible(true);
    }//GEN-LAST:event_modificarProveedorActionPerformed

    private void ConsuIndProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsuIndProvActionPerformed
        FConProveedor cp = new FConProveedor(adminPro);
        cp.setVisible(true);
    }//GEN-LAST:event_ConsuIndProvActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        FEliminarProd ep = new FEliminarProd(adminP);
        this.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        FGeneralProductos cg = new FGeneralProductos(adminP);
        cg.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        FELiminarVenta ev = new FELiminarVenta(adminCV, this, true);
        ev.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void MeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeClientesActionPerformed

    private void ConsultaIndClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaIndClienteActionPerformed
        FConClientes ci = new FConClientes(adminC);
        ci.setVisible(true);
    }//GEN-LAST:event_ConsultaIndClienteActionPerformed

    private void ModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarClienteActionPerformed
        FModificar mf = new FModificar(adminC);
        mf.setVisible(true);
    }//GEN-LAST:event_ModificarClienteActionPerformed

    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        FEliminarClustomer ec = new FEliminarClustomer(adminC);
        ec.setVisible(true);
    }//GEN-LAST:event_EliminarClienteActionPerformed

    private void ConsultGeneralClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultGeneralClientesActionPerformed
        FGeneralClientes gc = new FGeneralClientes(adminC);
        gc.setVisible(true);
    }//GEN-LAST:event_ConsultGeneralClientesActionPerformed

    private void consultaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaProveedorActionPerformed
        FGeneralProveedores gp = new FGeneralProveedores(adminPro);
        gp.setVisible(true);
    }//GEN-LAST:event_consultaProveedorActionPerformed

    private void EliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProveedorActionPerformed
        FEliminarProv ep = new FEliminarProv(adminPro);
        ep.setVisible(true);
    }//GEN-LAST:event_EliminarProveedorActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FProductos np = new FProductos(adminP, this, true);
        np.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        FProductosConsultaInd ci = new FProductosConsultaInd(adminP);
        ci.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        FModificarProd mpp = new FModificarProd(adminP, this, true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        NuevaVenta nv = new NuevaVenta(adminCV, this, true);
        nv.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        NuevaCompra nc = new NuevaCompra(adminCV, this, true);
        nc.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
      FGenerallVentas gv = new FGenerallVentas(adminCV);
      gv.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        FConsIndVentas civ = new FConsIndVentas(adminCV, this, true);
        civ.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        FELiminarCompra ec = new FELiminarCompra(adminCV, this, true);
        ec.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        FGeneralCompras fgc = new FGeneralCompras(adminCV);
        fgc.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        FConsIndCompras cic = new FConsIndCompras(adminCV, this, true);
        cic.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsuIndProv;
    private javax.swing.JMenuItem ConsultGeneralClientes;
    private javax.swing.JMenuItem ConsultaIndCliente;
    private javax.swing.JMenuItem EliminarCliente;
    private javax.swing.JMenuItem EliminarProveedor;
    private javax.swing.JMenu MeClientes;
    private javax.swing.JMenu MeCompras;
    private javax.swing.JMenu MeProd;
    private javax.swing.JMenu MeProv;
    private javax.swing.JMenu MeVentas;
    private javax.swing.JMenuItem ModificarCliente;
    private javax.swing.JMenuItem agregarCliente;
    private javax.swing.JMenuItem agregarProveedor;
    private javax.swing.JMenuItem consultaProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem modificarProveedor;
    // End of variables declaration//GEN-END:variables
}
